version: '3'

services:
  logs_template: &logs_template
    image: alpine
    logging:
      options:
        max-size: "5m"
        max-file: "7"

  volumes_template: &volumes_template
    image: alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  help_bot:
    <<: [*logs_template, *volumes_template]
    container_name: help_bot
    restart: unless-stopped
    build: .
    command: ["python", "main.py"]
    depends_on:
      - redis
      - celery

  redis:
    <<: [*logs_template, *volumes_template]
    container_name: help_bot_redis
    restart: unless-stopped
    image: "redis:alpine"

  celery:
    <<: [*logs_template, *volumes_template]
    build: .
    container_name: help_bot_celery
    restart: unless-stopped
    command: celery -A tasks worker -B --loglevel=debug
    depends_on:
      - redis
